Node version because 20 is not sufficient:
~/gg/app/shell/ErrorDialog.svelte:1:1
Error: Error in svelte.config.js

SyntaxError: The requested module 'node:util' does not provide an export named 'styleText' (svelte)
<script lang="ts">
    import ActionWidget from "../controls/ActionWidget.svelte";